# Generated by Django 3.2.7 on 2022-07-11 11:23

import cloudinary.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import safaris.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_tourist', models.BooleanField(default=False)),
                ('is_tourguide', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=100)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(default=254799735661, max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=safaris.models.User)),
                ('full_name', models.CharField(default='', max_length=255)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(default=254799735661, max_length=128, region=None, unique=True)),
                ('email', models.CharField(default='', max_length=255)),
                ('profile_image', cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/albrighthuman/image/upload/v1654536946/hjiaxew1u4pydlw3wljo.jpg', max_length=255, verbose_name='image')),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('address', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Safaris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=344)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=400)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='safais-image')),
                ('video', cloudinary.models.CloudinaryField(default=None, max_length=255, null=True, verbose_name='safaris-video')),
                ('Tourguide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safaris', to=settings.AUTH_USER_MODEL)),
                ('Tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safaris_tourist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/albrighthuman/image/upload/v1654536946/hjiaxew1u4pydlw3wljo.jpg', max_length=255, verbose_name='image')),
                ('bio', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(default=254799735661, max_length=128, region=None, unique=True)),
                ('name', models.IntegerField(default='')),
                ('email', models.CharField(blank=True, default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('Safaris', models.ManyToManyField(related_name='safaris_tourist', to='safaris.Safaris')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tourist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tourguide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True)),
                ('location', models.IntegerField(blank=True, default='')),
                ('address', models.CharField(default='', max_length=255)),
                ('company_bio', models.CharField(default='', max_length=255)),
                ('company_pic', cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/albrighthuman/image/upload/v1654439561/cld-sample-2.jpg', max_length=255, verbose_name='image')),
                ('Safaris', models.ManyToManyField(related_name='safaris', to='safaris.Safaris')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tourguide', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
