# Generated by Django 4.0.5 on 2022-07-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Safaris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=344)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=400)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='brian', upload_to='images/')),
                ('video', models.FileField(upload_to='video/%y')),
            ],
        ),
    ]
