# Generated by Django 4.0.5 on 2022-07-04 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safaris', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourguide',
            old_name='image',
            new_name='images',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('image_path', models.ImageField(upload_to='images/')),
                ('tourguide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safaris.tourguide')),
            ],
        ),
    ]
