# Generated by Django 3.2.7 on 2022-07-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safaris', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safaris',
            name='Tourist',
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='Safaris',
        ),
    ]
