# Generated by Django 3.2.7 on 2022-07-11 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safaris', '0004_auto_20220711_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaris',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='safaris', to=settings.AUTH_USER_MODEL),
        ),
    ]
