# Generated by Django 3.2.7 on 2022-07-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safaris', '0005_safaris_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safaris',
            name='user',
        ),
    ]
